#!/usr/bin/env bash
# init.sh — turn a fresh clone of this boilerplate into a working project skeleton.
#
#   scripts/init.sh "My Project" P3
#
# What it does:
#   1. Lays down docs/  ← running-files/,  docs/sops/ ← sops/,  docs/ci/ ← ci/
#   2. Substitutes «PROJECT NAME» throughout the copies
#   3. Writes harness.conf pointing at the new layout, so the gates run immediately
#   4. Generates docs/documentation-index.md from what it actually copied
#   5. Regenerates the doc-paths baseline against the real layout
#   6. PRINTS what your profile does not need — it never deletes
#
# ⛔ IT DELETES NOTHING. Pruning is a judgement call with a blast radius, so it prints a `git rm`
# list and stops. That is the same standing rule the harness applies to every destructive action:
# explain what it removes, then let a human decide. See TAILORING.md for the profiles.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
cd "$ROOT"

NAME="${1:-}"
PROFILE="${2:-P3}"

if [ -z "$NAME" ]; then
  echo "usage: scripts/init.sh \"<Project Name>\" [P1|P2|P3|P4|P5]" >&2
  echo "       see TAILORING.md — pick the SMALLEST profile that fits, then promote later." >&2
  exit 2
fi

case "$PROFILE" in P1|P2|P3|P4|P5) ;; *) echo "unknown profile: $PROFILE (want P1..P5)" >&2; exit 2 ;; esac

if [ -e docs ]; then
  echo "refusing to run: docs/ already exists." >&2
  echo "This looks like an already-initialised project. Move or remove docs/ first if you" >&2
  echo "really mean to re-init — that is your call to make, not this script's." >&2
  exit 1
fi

echo "── initialising '$NAME' at profile $PROFILE"

# ── 1. layout ────────────────────────────────────────────────────────────────
mkdir -p docs/sops docs/ci
cp -R running-files/. docs/
cp -R sops/.          docs/sops/
cp -R ci/.            docs/ci/

# ── 2. project name ──────────────────────────────────────────────────────────
# BSD sed needs the -i backup arg; GNU does not. Write to a temp file to stay portable.
subst() {
  # Two statements, deliberately: bash expands ALL words of a single `local` before any of its
  # assignments take effect, so `local f="$1" tmp="$f..."` sees an unset $f and dies under `set -u`.
  local f="$1"
  local tmp="$f.init.$$"
  sed -e "s/«PROJECT NAME»/$NAME/g" -e "s/«PROJECT»/$NAME/g" "$f" > "$tmp" && mv "$tmp" "$f"
}
find docs -name '*.md' -type f | while IFS= read -r f; do subst "$f"; done
[ -f CLAUDE.md ] && subst CLAUDE.md

# ── 3. config ────────────────────────────────────────────────────────────────
cat > harness.conf <<CONF
# harness.conf — $NAME (profile $PROFILE). Generated by scripts/init.sh.
# Every option + what it does: harness.conf.example

HARNESS_DOC_DIRS="docs"
HARNESS_DOC_INDEX="docs/documentation-index.md"

# ⚠ SET THESE — the gates cover nothing until they point at real source.
HARNESS_CODE_DIRS="src"
HARNESS_CODE_EXTS="go ts tsx js rs py java rb"

HARNESS_DECISION_DIR="docs/adr"
HARNESS_DECISION_PREFIX="ADR"
HARNESS_DECISION_LEDGER=""

HARNESS_BUG_REGISTER="docs/tickets/bug-register.md"
HARNESS_MARKERS="DEFERRED-TEST:docs/deferred-test-registry.md"

HARNESS_SECRET_TERMS="password passwd secret token apikey api_key privatekey private_key seed mnemonic otp pin ssn"
HARNESS_LOG_FUNCS="log logf print println debug info warn error fatal trace"

# ⚠ SET THESE — empty means the suite reports NOT RUN, which is a gap, not a pass.
HARNESS_TEST_CMD=""
HARNESS_COVERAGE_CMD=""
HARNESS_LINT_CMD=""
HARNESS_TEST_ENV_GATES=""

HARNESS_BASELINE_DIR=".harness/baselines"
HARNESS_BASE_REF="origin/main"
CONF

# ── 4. doc index ─────────────────────────────────────────────────────────────
{
  echo "# Documentation index — $NAME"
  echo
  echo "> Every living doc is registered here, with its update trigger. A doc nobody registered"
  echo "> is a doc nobody will update — and it will still be read. Gated by \`scripts/check-doc-index.sh\`."
  echo
  echo "| Doc | What it holds | Update when |"
  echo "|---|---|---|"
  find docs -name '*.md' -type f | sort | while IFS= read -r f; do
    [ "$f" = "docs/documentation-index.md" ] && continue
    title="$(head -1 "$f" | sed 's/^#[[:space:]]*//')"
    echo "| \`$f\` | ${title:-«what it holds»} | «trigger» |"
  done
} > docs/documentation-index.md

# ── 5. baseline against the REAL layout ──────────────────────────────────────
rm -rf .harness/baselines
bash "$HERE/check-doc-paths.sh" --write-baseline >/dev/null 2>&1 || true

# ── 6. what this profile does not need ───────────────────────────────────────
echo
echo "── profile $PROFILE: review these for removal (NOTHING was deleted)"
prune() { [ -e "$1" ] && echo "   git rm -r $1   # $2"; }

case "$PROFILE" in
  P1)
    prune docs/tickets              "P1: no ticket taxonomy for a throwaway"
    prune docs/adr                  "P1: decisions can be a section in ONBOARDING.md"
    prune docs/runner.md            "P1: no wave runner"
    prune docs/feature-catalog.md   "P1"
    prune docs/use-case-runbook.md  "P1"
    prune docs/sops                 "P1: core only"
    ;;
  P2)
    prune docs/tickets                          "P2: until something needed from a human gets lost"
    prune docs/runner.md                        "P2: until >1 workstream is in flight"
    prune docs/use-case-runbook.md              "P2: no end-user flows in a library"
    prune docs/sops/ui-development-guardrails.md "P2: no UI"
    prune docs/sops/mockup-implementation.md    "P2: no designs"
    prune docs/sops/security-properties.md      "P2: no network surface / multi-user"
    prune docs/sops/owner-communication.md      "P2: no non-technical stakeholder"
    ;;
  P3)
    prune docs/sops/security-properties.md "P3: keep ONLY if multi-user, network surface, or untrusted input"
    prune docs/ci/run-integrity.md         "P3: keep once any job has >1 stage"
    ;;
  P4) echo "   (P4 keeps nearly everything — prune only what plainly does not apply)" ;;
  P5) echo "   (P5 keeps everything)" ;;
esac
[ "$PROFILE" != "P3" ] && [ "$PROFILE" != "P4" ] && [ "$PROFILE" != "P5" ] && \
  prune docs/ci/run-integrity.md "no multi-stage jobs yet"

cat <<NEXT

── next, in order (TAILORING.md has the detail)

  1. Fill every «SLOT» in CLAUDE.md — ESPECIALLY the invariants. If you cannot name 1-3 things
     that must never break, you are not ready to set coverage targets or write guardrail tests.
  2. Set HARNESS_CODE_DIRS and HARNESS_TEST_CMD in harness.conf. Until then the gates cover
     nothing, and they will say so rather than reporting green.
  3. Cut CLAUDE.md's standing rules to the ones you will actually enforce. A rule nobody
     enforces teaches the agent that rules here are decorative.
  4. Run:  scripts/run-all-gates.sh
  5. VERIFY THE GATES before trusting any of them:
        scripts/selftest.sh   — does the G7 half: plants a violation per gate, asserts each
                                goes red, then recovers. Run it after touching any gate.
        G8 wiring             — do this half yourself: trigger a gate the way production
                                will. Calling the script proves only the script.
  6. Wire scripts/hook-fast-gates.sh into your agent harness, then confirm you have SEEN it
     fire this session (docs/ci/control-timing.md C3 — an unloaded hook is invisible).
  7. Write the enforced-vs-unenforced table into CLAUDE.md (control-timing.md C5), honestly.

  This kit's own meta files (README.md, TAILORING.md, running-files/, sops/, ci/, harness.conf.example)
  are now duplicated under docs/. Remove the originals when you are ready:  git rm -r running-files sops ci

NEXT
